name: Lint and Prettier
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Get yarn cache directory path
          id: yarn-cache-dir-path
          run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run ESLint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint . --ext .js,.jsx,.ts,.tsx
      - name: Prettify Code
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier --write .

