name: Lint and Prettier
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run ESLint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint . --ext .js,.jsx,.ts,.tsx
      - name: Check Prettier
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier --check .
      - name: Prettify Code
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier --write .

