name: Lint and Prettier
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts'
      - name: Install dependencies
        run: npm run install
      - name: Run ESLint
        run: npm run eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run Prettier
        run: npm run prettier --check .

